from .TSStruct import * 
TCANQueueEvent_API = WINFUNCTYPE(None,PLIBCAN)
TGPSQueueEvent_Win32 = WINFUNCTYPE(None,ps32,PLIBGPSData)
TCANQueueEvent_Win32 = WINFUNCTYPE(None,ps32,PLIBCAN)
TCANFDQueueEvent_Win32 = WINFUNCTYPE(None,ps32,PLIBCANFD)
TFlexRayQueueEvent_Win32 = WINFUNCTYPE(None,ps32,PLIBFlexRay)
TEthernetQueueEvent_Win32 = WINFUNCTYPE(None,ps32,PLIBEthernetHeader)
TLINQueueEvent_Win32 = WINFUNCTYPE(None,ps32,PLIBLIN)
TLIBTSMasterLogger = WINFUNCTYPE(None,pchar,s32)
TFirmwareUpdateCallback = WINFUNCTYPE(None,TObject,u32,single)
TOnIoIPData = WINFUNCTYPE(None,ps32,s32)
TOnIoIPData_API = WINFUNCTYPE(None,ps32,s32)
TOnIoIPConnection = WINFUNCTYPE(None,pchar,s32)
TOnIoIPConnection_API = WINFUNCTYPE(None,pchar,s32)
TLIBWriteAPIDocumentFunc = WINFUNCTYPE(None,ps32,pchar,pchar,pchar,pchar,s32)
TLIBWriteAPIParaFunc = WINFUNCTYPE(None,ps32,s32,pchar,pchar,c_bool,pchar,pchar)
TLIBWriteAPIDocument = WINFUNCTYPE(None,ps32,TLIBWriteAPIDocumentFunc,TLIBWriteAPIParaFunc)
TLIBOnSysVarChange = WINFUNCTYPE(None,pchar)
TReadProgressCallback = WINFUNCTYPE(None,ps32,double)
N_USData_TranslateCompleted_Recall = WINFUNCTYPE(None,s32,s32,u64,pu8,u32,s32)
N_USData_TranslateCompleted_Recall_Obj = WINFUNCTYPE(None,s32,s32,u8,s32,s32,u64,pu8,u32,s32)
TLogDebuggingInfo = WINFUNCTYPE(None,pchar,s32)
tosun_recv_callback = WINFUNCTYPE(None,s32,ps32,u16)
tosun_tcp_presend_callback = WINFUNCTYPE(None,s32,ps32,Pip_addr_t,Pip_addr_t,u8,u8)
tosun_tcp_ack_callback = WINFUNCTYPE(None,s32,ps32,u16)
